import _ from 'lodash'

function component() {
    console.log("Hello WebPack")
    const element = document.createElement('div')   
    element.innerHTML = _.join(["Hello", "Webpack"], " ")
    return element;
}

/**
 * If the `component` function is not used or invoked, it will not 
 * be included in the final JavaScript bundle generated by Webpack. 
 * This optimization is known as tree-shaking or dead code elimination.
 * 
 * To test this, try commenting out both of the following invocations 
 * of `component()`:
 * 
 * - `document.body.appendChild(component());`
 * - `component();`
 * 
 * After doing so, check the final bundle to confirm if Webpack has 
 * removed the `component` function.
 */

document.body.appendChild(component());
component();
